config/routes.rb
Rails.application.routes.draw do
  resources :pets, only: [:index, :show]
  resources :stores, only: [:index, :show]
  resources :users
  resources :appointments, only: [:index, :show, :new, :create]
  resources :reviews, only: [:index, :show, :new, :create]
  resources :sessions, only: [:new, :create, :destroy, :show]

  # Welcome/Login/Logut Routes
  root to: "static#mission"
  get "/signup", to: "users#new", as: "signup"
  get "/login", to: "sessions#new", as: "login"
  get "/logout", to: "sessions#destroy", as: "logout"
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/store.rb
class Store < ApplicationRecord
    # ActiveRecord Relationships
    has_many(:pets)
    has_many(:appointments, through: :pets)

    # Validations
    validates(:name, :address, presence: true)
    validates(:address, uniqueness: true)

    # Class Instance Methods
    def pets_count
        self.pets.count
    end

    # Class Methods
    def self.all_name_ordered
        self.order(name: :asc)
    end

end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
    # Action/Route Filters
    before_action(:assign_store, only: [:show])

    # Action/Route Methods
    def index
        @stores = Store.all_name_ordered
    end

    def show
    end

    # Private Class Instance Helper Methods
    private
    def assign_store
        @store = Store.find(params[:id])
    end

end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/index.html.erb
<div class="h1 text-center"> <h1>All Stores</h1></div>

<br>
<br>
<br>
<br>
<ul class="list-group-item text-center ">
   <div class="flex-column">
  
  <% @stores.each do |store| %>
  <li class="list-group-item"><%= link_to(store.name, store_path(store)) %><br>
  <%= pluralize(store.pets_count, "pet")%></li>
  
  <% end %>
  </div>
</ul>

app/views/stores/show.html.erb
<br>
<br>

<div class="card" style="width: 18rem;">
 
  <div class="card-body">
    <h5 class="card-title"><h1><%= @store.name %><h1></h5>
    <h4 class="card-text">Contact Information</h4><br>
    <li class="card-text">Address: <%= @store.address %></li>
  </div>

  <ul class="list-group list-group-flush">
    <h5 class="list-group-item">Available Pets (<%= @store.pets_count %>)</h5>
    <li class="list-group-item"><ul>
    <% @store.pets.all_name_ordered.each do |pet| %>
        <li><%= link_to(pet.name, pet_path(pet)) %> (Average Rating: <%=pet.average_review_rating%>)</li>
    <% end %>
</ul></li>
    
</div>