config/routes.rb
Rails.application.routes.draw do
  resources :pets, only: [:index, :show]
  resources :stores, only: [:index, :show]
  resources :users
  resources :appointments, only: [:index, :show, :new, :create]
  resources :reviews, only: [:index, :show, :new, :create]
  resources :sessions, only: [:new, :create, :destroy, :show]

  # Welcome/Login/Logut Routes
  root to: "static#mission"
  get "/signup", to: "users#new", as: "signup"
  get "/login", to: "sessions#new", as: "login"
  get "/logout", to: "sessions#destroy", as: "logout"
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    # Rails Password Encryption
    has_secure_password

    # ActiveRecord Relationships
    has_many(:appointments)
    has_many(:reviews)
    has_many(:pets, through: :appointments)

    # Validations
    validates(:username, :phone, :address, :password, :password_confirmation, presence: true)
    validates(:username, uniqueness: true) 
    validates(:password, confirmation: true)

    # Class Instance Methods
    def upcoming_appointments
        Appointment.where("user_id = ? AND check_out >= ?", self.id, DateTime.now).order(check_out: :asc)
    end

    def upcoming_appointments_count
        self.upcoming_appointments.count
    end

    def previous_appointments
        Appointment.where("user_id = ? AND check_out < ?", self.id, DateTime.now).order(check_out: :desc)
    end

    def previous_appointments_count
        self.previous_appointments.count
    end

    def reviews_count
        self.reviews.count
    end

    def reviews_date_ordered
        self.reviews.order(updated_at: :desc)
    end

    def pets_count
        self.pets.uniq.count
    end
    # Class Methods
    def self.all_username_ordered
        self.order(username: :asc)
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    # Action/Route Filters
    before_action(:assign_user, only: [:show, :edit, :update, :destroy])
    before_action(:require_login, except: [:index, :new, :create])

    # Action/Route Methods
    def index
        @users = User.all_username_ordered
    end

    def show
    end

    def new
        !!params[:user] ? @user = User.new(user_params) : @user = User.new
    end

    def create
        @user = User.create(user_params)
        if @user.valid?
            # Login User the redirect to their show page
            session[:user_id] = @user.id
            redirect_to(user_path(@user))
        else
            flash[:errors] = @user.errors.full_messages
            redirect_to(new_user_path(user: user_params))
        end
    end

    def edit
    end

    def update
        @user.update(user_params)
        if @user.valid?
            redirect_to(user_path(@user))
        else
            flash[:errors] = @user.errors.full_messages
            redirect_to(edit_user_path(@user))
        end
    end

    def destroy
        @user.destroy
        redirect_to(users_path)
    end

    # Private Class Instance Helper Methods
    private
    def assign_user
        @user = User.find(params[:id])
    end

    def user_params
        params.require(:user).permit(:username, :phone, :address, :password, :password_confirmation)
    end

    def require_login
        if current_user
            if current_user.username == "Admin"
                # Admin is logged in
            else
                # Only allow users to look at their pages
                return head(:forbidden) unless current_user.id == @user.id
            end
        else
            # No user is logged in
            head(:forbidden)
        end
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<% if !!flash[:errors] %>
    <ul style = "color: red">
    <% flash[:errors].each do |error| %>
        <li><%= error %></li>
    <% end %>
    </ul>
<% end %>

<%= form_with(model: @user) do |f| %>
    <%= f.label(:username) %>
    <%= f.text_field(:username) %>
    <br>
    <%= f.label(:phone) %>
    <%= f.telephone_field(:phone) %>
    <br>
    <%= f.label(:address) %>
    <%= f.text_field(:address) %>
    <br>
    <%= f.label(:password) %>
    <%= f.password_field(:password) %>
    <br>
    <%= f.label(:password_confirmation) %>
    <%= f.password_field(:password_confirmation) %>
    <br>
    <%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<div class="h1 text-center"><h1>Edit User</h1></div>

<div class="center-form text-center"><%= render('form') %></div>

app/views/users/index.html.erb
<div class="h1 text-center"> 
<h1 >Available Users</h1></div>

<ul class="list-group-item text-center ">
   <div class="flex-column">
  <li class="list-group-item"><%= link_to('Create New User', new_user_path) %></li>
  <% @users.each do |user| %>
  <li class="list-group-item"><%= link_to(user.username, user_path(user)) %><br>
  <%= pluralize(user.pets_count, "Rented Pet") %><br>
  <%= pluralize(user.upcoming_appointments_count, "Upcoming Appointment") %></li>
  
  <% end %>
  </div>
</ul>

app/views/users/new.html.erb
<div class="h1 text-center"> <h1>Create New User</h1></div>

<div class="center-form text-center"><%= render('form') %></div>

app/views/users/show.html.erb
<div class="card" style="width: 18rem;">
 <div class="card-body">
      <h3 class="card-title"><%= @user.username %></h3></div>
    
  <div class="list-group list-group-flush">
  <h4>Contact Information</h4>
    <li class="list-group-item">Phone: <%= @user.phone %></li>
    <li class="list-group-item">Address: <%= @user.address %></</li>
    <li class="list-group-item"><%= link_to('Edit', edit_user_path(@user)) %> or 
    <%= link_to('Delete', user_path(@user), method: :delete, data: { confirm: 'Are you sure?' }) %> Contact Info</li>
  </div>
  
  <div class="card-body">
        <h3 class="card-title">Upcoming Appointments (<%=@user.upcoming_appointments_count%>)</h3>
    
        <ul>
            <% @user.upcoming_appointments.each do |appointment| %>
            <li><%= link_to(appointment.summary, appointment_path(appointment)) + ": " + link_to(appointment.pet.name, pet_path(appointment.pet)) %></li>
                <% end %>
        </ul>

  </div>
  <ul class="list-group list-group-flush">
    
 
  </ul>

  <div class="card-body">
       <br> <h3 class="card-title">Previous Appointments (<%=@user.previous_appointments_count%>)</h3>
    
        <ul>
            <% @user.previous_appointments.each do |appointment| %>
            <li><%= link_to(appointment.summary, appointment_path(appointment)) + ": " + link_to(appointment.pet.name, pet_path(appointment.pet)) %></li>
                <% end %>
        </ul>

  </div>
  
  
  <ul class="list-group list-group-flush">
    
 
  </ul>

  
    <div class="card-body">
        <h3 class="card-title">Written Reviews (<%=@user.reviews_count%>)</h3>
        <ul>
            <% @user.reviews_date_ordered.each do |review| %>
            <li><%= link_to(review.title , review_path(review))%></li>
        <ul>
           <li>Pet: <%= link_to(review.pet.name, pet_path(review.pet)) %></li>
         <li>Rating: <%= review.rating %></li>
            <li>Updated: <%= review.updated_at%>
        </ul>
            <% end %>

  </div>

  <a <%= link_to('New Appointment', new_appointment_path)%></a><br>

 <a <%= link_to('Add Pet Review', new_review_path) %></a><br>
  
<%= link_to('Logout', logout_path) %></a><br>
<br>
</div>