config/routes.rb
Rails.application.routes.draw do
  resources :pets, only: [:index, :show]
  resources :stores, only: [:index, :show]
  resources :users
  resources :appointments, only: [:index, :show, :new, :create]
  resources :reviews, only: [:index, :show, :new, :create]
  resources :sessions, only: [:new, :create, :destroy, :show]

  # Welcome/Login/Logut Routes
  root to: "static#mission"
  get "/signup", to: "users#new", as: "signup"
  get "/login", to: "sessions#new", as: "login"
  get "/logout", to: "sessions#destroy", as: "logout"
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    # Action/Route Methods
    def index
        @reviews = Review.all_rating_ordered
    end

    def show
        @review = Review.find(params[:id])
    end

    def new
        !!params[:review] ? @review = Review.new(review_params) : @review = Review.new
    end

    def create
        @review = Review.create(review_params)
        if @review.valid?
            redirect_to review_path(@review)
        else
            flash[:errors] = @review.errors.full_messages
            redirect_to(new_review_path(review: review_params))
        end
    end

   # Private Class Instance Helper Methods
    private

    def review_params
        params.require(:review).permit(:pet_id, :user_id, :title, :content, :rating)
    end
end

app/views/reviews/index.erb
<div class="h1 text-center"> 
<h1>Pet Reviews</h1></div>
 <div class="h3 text-center"><%= link_to('Create New Review', new_review_path) %></div>

<ul class="list-group-item text-center ">
<div class="flex-column">

   <% @reviews.each do |review| %>
      <li class="list-group-item"><%= link_to review.title, review_path(review) %><br> 
      
         <li>Rating: <%= review.rating %><br>
          <li class="list-group-item"></li>User: <%= link_to(review.user.username, user_path(review.user)) %></li>
         <li>Pet: <%= link_to(review.pet.name, pet_path(review.pet)) %></li>
      
   <% end %>
   </div>
</ul>
<br>
<br>



  
  
  

app/views/reviews/new.html.erb
<div class="h1 text-center"><h1>New Review</h1></div>

<% if !!flash[:errors] %>
    <ul style = "color: red">
    <% flash[:errors].each do |error| %>
        <li><%= error %></li>
    <% end %>
    </ul>
<% end %>

<div class="h3 text-center"><%= form_with(model: @review) do |f| %>
    <%= f.label(:user) %>
    <%= f.collection_select(:user_id, User.all_username_ordered, :id, :username) %>
    <br>
    <%= f.label(:pet) %>
    <%= f.collection_select(:pet_id, Pet.all_name_ordered, :id, :name) %>
    <br>
    <%= f.label(:title) %>
    <%= f.text_field(:title) %>
    <br>
    <%= f.label(:content) %>
    <%= f.text_area(:content) %>
    <br>
    <%= f.label(:rating) %>
    <%= f.number_field(:rating, in: (1..5)) %>
    <br>
    <%= f.submit %></div>
<% end %>

app/views/reviews/show.erb
<br>
<br>

<div class="card" style="width: 18rem;">
  
  <div class="h1 text-center"><h1><%= @review.title %></h1></div>
   
 
  <ul class="list-group list-group-flush">
    <li class="list-group-item text-center">Rating: <%= @review.rating %></li>
    <li class="list-group-item">User: <%= link_to(@review.user.username, user_path(@review.user)) %></li>
    <li class="list-group-item">Pet: <%= link_to(@review.pet.name, pet_path(@review.pet)) %></li>
    <li class="list-group-item">Pet: Date: <%= @review.date %></li>
    <li class="list-group-item"><%= @review.content %></li>
  </ul>
 
</div>