config/routes.rb
Rails.application.routes.draw do
  resources :pets, only: [:index, :show]
  resources :stores, only: [:index, :show]
  resources :users
  resources :appointments, only: [:index, :show, :new, :create]
  resources :reviews, only: [:index, :show, :new, :create]
  resources :sessions, only: [:new, :create, :destroy, :show]

  # Welcome/Login/Logut Routes
  root to: "static#mission"
  get "/signup", to: "users#new", as: "signup"
  get "/login", to: "sessions#new", as: "login"
  get "/logout", to: "sessions#destroy", as: "logout"
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rent-A-Pet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <style>
body  {
  background-image: url(https://media.gettyimages.com/videos/pets-pattern-scrolling-background-with-colored-paws-video-id1128160003?s=640x640);
  
}
</style>
  </head>

  <body> 
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Rent-A-Pet</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto nav-fill w-100">
      <li class="nav-item active">
         <a class="nav-link" <%= link_to("Home", root_path)%></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" <%= link_to("View Our Pets", pets_path)%></a> 
      </li>
       
       <li class="nav-item">
        <a class="nav-link"   <a <%= link_to('New Appointment', new_appointment_path)%></a>
      </li>
      <li class="nav-item">
        <a class="nav-link"   <a <%= link_to('Locations', stores_path)%></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" <%= link_to("Login", login_path)%></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" <%= link_to("Sign up", signup_path)%></a>
      </li>
       <li class="nav-item">
        <a class="nav-link" <%= link_to("Log Out", logout_path)%></a>
      </li>
      
      
    </ul>
    
  </div>
</nav>


    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>